server:
  port: 8080

spring:
  application:
    name: solution-back
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/solution_seguros
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        enabled: true
        options:
          model: models/gemini-3-flash-preview
      embedding:
        enabled: true
        options:
          model: models/gemini-embedding-001
          dimensions: 768

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: HNSW

logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR

audit:
  approve-threshold: 70   # riskScore >= 70 → APPROVE
  rules-version: "1.0.0"

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc3Ryb25nLXNlY3JldC1rZXktZm9yLWF1ZGl0LVNlZ3Vyb3MtMjAyNA==}
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html